### ISSUE TITLE
A reference voltage should be added

### ISSUE THREAD

**Issue by e-i-s-e** [upb-lea/LCB-CDB-01_Dock_Board#1]
A reference voltage of 3.0V should be added to this board.
The daughter board "LCB-CCB-01" uses a reference voltage of 3.0V for its AD converters.

Thus the currently used 3.3V, as voltage supply for potentiometers, etc., are not well suited.

**Comment by gituser789** [comment]
fixed with 928d374772afce94c0703ff6c73f3d4d2d397195
